title: Suzanne Eisenberg Portfolio
description: A compilation of coding projects and interactive designs created by Suzanne Eisenberg
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
